### ISSUE TITLE
Windows file desktop.ini crashes script

### ISSUE THREAD

**Issue by Roland0711** [yui-tan/pyPromptChecker#9]
Hi,

thank you for your nice script!
It work with single files on windows very well.
But with dirs it crashed cause of the existence of  hidden "desktop.ini" in every Windows-Dir.

The error messages:
This is directory
Do I have to start explaining the difference between files and directories?

P:/AI/Bilder\desktop.ini
These files are not PNG images.
You'd better to learn or relearn what a PNG file is.

a hoy!!!!
QApplication::regClass: Registering window class 'Qt652ScreenChangeObserverWindow' failed. (Klasse ist bereits vorhanden)
Traceback (most recent call last):
  File "P:\AI\pyPromptChecker\venv\Scripts\mikkumiku-script.py", line 33, in <module>
    sys.exit(load_entry_point('pyPromptChecker', 'console_scripts', 'mikkumiku')())
  File "p:\ai\pypromptchecker\pyPromptChecker\main.py", line 107, in main
    window.from_main('result', valid_filepath)
  File "p:\ai\pypromptchecker\pyPromptChecker\gui\window.py", line 452, in from_main
    result_window = ResultWindow(target_data)
  File "p:\ai\pypromptchecker\pyPromptChecker\gui\window.py", line 23, in __init__
    self.init_ui(targets)
  File "p:\ai\pypromptchecker\pyPromptChecker\gui\window.py", line 59, in init_ui
    if parameters.params['Positive'] == 'This file has no embedded data' and ignore:
KeyError: 'Positive'

and the errormessages for the EXE with "-a":

Traceback (most recent call last):
  File "pyPromptChecker\main.py", line 111, in <module>
    main()
  File "pyPromptChecker\main.py", line 107, in main
    window.from_main('result', valid_filepath)
  File "pyPromptChecker\gui\window.py", line 452, in from_main
    result_window = ResultWindow(target_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pyPromptChecker\gui\window.py", line 23, in __init__
    self.init_ui(targets)
  File "pyPromptChecker\gui\window.py", line 59, in init_ui
    if parameters.params['Positive'] == 'This file has no embedded data' and ignore:
       ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'Positive'

By the way, please do me a favor and skip the teachings. 
Like: "Do I have to start explaining ..." / "You'd better to learn.."
You don't know who is using your program. I find it disrespectful.

**Comment by yui-tan** [comment]
Thanks for reporting bugs.
I don't think this issue causes by 'desktop.ini'.
because looking a log the script correctly judged that 'desktop.ini' is not image file.

I noticed other issue around directory treatment hours ago.
I'm on Linux but I doubt the same reason as this.
If you are using source code editions, please "git pull" and try it again.
If not, please wait a bit for new binary... 

And I'm sorry about that error messages. 
The messages is from a time when the script was personal use to me. 
I forgot delete it. 
Sorry to make you feel uncomfortable.

**Comment by Roland0711** [comment]
Thank you for your fast responce and change!

And you are right, the problem ist not the desktop.ini.
I can now reproduche the problem better: 
For some reason the "EXTRAS" scaler produce with the scale of 4x and  some of the upscaler an additional .jpg picture.
This has as comment the last action, eg. "Postprocess upscale by: 4, Postprocess upscaler: R-ESRGAN 4x+" same with "upscaler: 4x-UltraSharp". This seems only happen by 4times upscale. 
If I remove the comment the Problem is gone. If afterwards any comment is added, the problen does not reoccure.

A simple testfile:
![00026](https://github.com/yui-tan/pyPromptChecker/assets/142908495/615065f6-e276-483b-8ffd-c00645682d28)

Hope this helps

**Comment by Roland0711** [comment]
It works, thank you for your kind and fast support!
